# 如果你需要新增端口映射
# 可以在这里添加新的 server 块，确保端口号和容器内的服务端口一致
# 并在 docker-compose.yml 中添加相应的端口映射
# 并仅对 nginx 进行重启
# 从而避免重启整个alx服务
server {
    listen 17390;
    server_name localhost;
    location / {
        proxy_pass http://alx:17390;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}