import { ArrowUp, Bot, Mic, Paperclip, Send, Settings2, SlidersHorizontal, X } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'

type Provider = { id: string; name: string; baseURL: string; model: string; hasKey: boolean }
type Message = { role: 'user' | 'assistant'; content: string }

// The embedded page is intentionally only the conversation surface. Provider
// settings are kept out of this first interaction so opening AI never becomes
// a configuration flow.
export function AIChatPage({ root }: { root: string }) {
  const [prompt, setPrompt] = useState('')
  const [messages, setMessages] = useState<Message[]>([])
  const [attachments, setAttachments] = useState<File[]>([])
  const [access, setAccess] = useState<'ask' | 'read' | 'full'>('ask')
  const [accessOpen, setAccessOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const fileInput = useRef<HTMLInputElement>(null)
  const accessLabel = { ask: '操作前询问', read: '仅查看', full: '完全访问' }[access]
  const attach = (files: FileList | null) => { const next = Array.from(files ?? []).filter(file => file.size <= 5 * 1024 * 1024).slice(0, 3); if (!next.length) { setNotice('请选择不超过 5 MB 的文件。'); return }; setAttachments(value => [...value, ...next].slice(0, 3)); setNotice(`已附加 ${next.length} 个文件。`) }
  const submit = () => { if (!prompt.trim()) return; const suffix = attachments.length ? `\n\n附件：${attachments.map(file => file.name).join('、')}` : ''; setMessages(value => [...value, { role: 'user', content: prompt.trim() + suffix }]); setPrompt(''); setAttachments([]); setNotice('消息已加入对话。配置 AI 接口后将开始生成回复。') }
  const voice = () => { const Recognition = (window as Window & { SpeechRecognition?: new () => { lang: string; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: (() => void) | null; start: () => void }; webkitSpeechRecognition?: new () => { lang: string; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: (() => void) | null; start: () => void } }).SpeechRecognition ?? (window as Window & { webkitSpeechRecognition?: new () => { lang: string; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onerror: (() => void) | null; start: () => void } }).webkitSpeechRecognition; if (!Recognition) { setNotice('当前浏览器不支持语音输入。'); return }; const recognition = new Recognition(); recognition.lang = 'zh-CN'; recognition.onresult = event => setPrompt(value => `${value}${value ? ' ' : ''}${event.results[0][0].transcript}`); recognition.onerror = () => setNotice('语音识别未完成，请检查麦克风权限。'); recognition.start(); setNotice('正在听…') }
  return <section className="ai-chat-page"><header><div><Bot /><span><small>{root}</small></span></div><button className="icon-button" onClick={() => setNotice('AI 接口设置即将提供。')} title="AI 设置"><Settings2 /></button></header><section className="ai-messages">{messages.length === 0 && <div className="ai-empty"><Bot /><h2>从这里开始处理项目</h2><p>描述修改目标、贴入报错，或让我先查看当前机器人目录。</p></div>}{messages.map((item,index)=><article className={item.role} key={index}>{item.content}</article>)}</section><footer className="ai-composer"><div className="ai-composer-frame"><textarea value={prompt} onChange={event => setPrompt(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} placeholder="Do anything"/><input ref={fileInput} className="ai-file-input" type="file" multiple onChange={event => attach(event.target.files)} /><div className="ai-composer-tools"><div><button className="icon-button" onClick={() => fileInput.current?.click()} title="附加文件"><Paperclip /></button><div className="ai-access-wrap"><button className="ai-access" onClick={() => setAccessOpen(value => !value)}><SlidersHorizontal /> {accessLabel}</button>{accessOpen && <div className="ai-access-menu">{([['ask', '操作前询问'], ['read', '仅查看'], ['full', '完全访问']] as const).map(([id, label]) => <button className={access === id ? 'active' : ''} key={id} onClick={() => { setAccess(id); setAccessOpen(false); setNotice(`权限已切换为：${label}。`) }}>{label}</button>)}</div>}</div></div><div className="ai-composer-actions"><button className="ai-model-button" onClick={() => setNotice('请先配置 AI 接口，随后可在此切换模型。')}>未配置模型 <small>⌄</small></button><button className="icon-button" onClick={voice} title="语音输入"><Mic /></button><button className="ai-send" disabled={!prompt.trim()} onClick={submit} aria-label="发送"><ArrowUp /></button></div></div>{attachments.length > 0 && <div className="ai-attachments">{attachments.map(file => <button key={file.name} onClick={() => setAttachments(value => value.filter(item => item !== file))}>{file.name} ×</button>)}</div>}</div>{notice && <small className="ai-composer-notice">{notice}</small>}</footer></section>
}

export function AIControl({ root }: { root?: string }) {
  const [open, setOpen] = useState(false); const [providers, setProviders] = useState<Provider[]>([])
  const [provider, setProvider] = useState('openai'); const [settings, setSettings] = useState(false)
  const [model, setModel] = useState(''); const [baseURL, setBaseURL] = useState(''); const [apiKey, setAPIKey] = useState('')
  const [messages, setMessages] = useState<Message[]>([]); const [prompt, setPrompt] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const current = providers.find(item => item.id === provider)
  const load = useCallback(async () => { const res = await fetch('/api/v1/ai/providers'); const data = await res.json() as Provider[]; setProviders(data); const item = data.find(value => value.id === provider) ?? data[0]; if (item) { setProvider(item.id); setModel(item.model); setBaseURL(item.baseURL) } }, [provider])
  useEffect(() => { if (open) void load() }, [open, load])
  useEffect(() => { if (current) { setModel(current.model); setBaseURL(current.baseURL); setAPIKey('') } }, [current])
  const save = async () => { setBusy(true);setError(''); try { const res=await fetch('/api/v1/ai/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,model,baseURL,apiKey})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error);await load();setSettings(false) }catch(reason){setError(reason instanceof Error?reason.message:'配置保存失败。')}finally{setBusy(false)} }
  const send = async () => { if (!prompt.trim() || !current?.hasKey) return; const next=[...messages,{role:'user' as const,content:prompt.trim()}];setMessages(next);setPrompt('');setBusy(true);setError('');try { const res=await fetch('/api/v1/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,messages:next})}); const data=await res.json() as {answer?:string;error?:string};if(!res.ok)throw new Error(data.error);setMessages([...next,{role:'assistant',content:data.answer||'没有返回内容。'}]) }catch(reason){setError(reason instanceof Error?reason.message:'AI 请求失败。')}finally{setBusy(false)} }
  return <div className="ai-control"><button className="ai-control-button" onClick={()=>setOpen(true)} aria-label="打开 AI 对话" title="AI 对话"><Bot /></button>{open&&<section className="ai-workspace"><header><div><Bot /><span><strong>AI 助手</strong><small>{root || '当前运行目录'}</small></span></div><div><button className="icon-button" onClick={()=>setSettings(value=>!value)} title="AI 设置"><Settings2 /></button><button className="icon-button" onClick={()=>setOpen(false)} title="关闭 AI"><X /></button></div></header><main>{settings||!current?.hasKey?<section className="ai-settings"><div className="ai-config-tabs">{providers.map(item=><button key={item.id} className={provider===item.id?'active':''} onClick={()=>setProvider(item.id)}>{item.name}<small>{item.hasKey?'已配置':'未配置'}</small></button>)}</div><h2>接口配置</h2><p>每个接口独立保存地址与 API Key；模型会在开始对话时根据所选接口获取。</p><label>接口地址<input value={baseURL} onChange={e=>setBaseURL(e.target.value)} /></label><label>API Key<input type="password" value={apiKey} onChange={e=>setAPIKey(e.target.value)} placeholder={current?.hasKey?'重新填写以更新密钥':'填写 API Key'} /></label><button className="primary-button" disabled={busy||!apiKey} onClick={()=>void save()}>{busy?'保存中…':'保存配置'}</button></section>:<><section className="ai-chat-head"><select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.filter(item=>item.hasKey).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><span>{current?.model}</span></section><section className="ai-messages">{messages.length===0&&<div className="ai-empty"><Bot /><h2>有什么可以帮你？</h2><p>当前目录：{root || '当前运行目录'}</p></div>}{messages.map((item,index)=><article className={item.role} key={index}>{item.content}</article>)}{busy&&<article className="assistant">正在思考…</article>}</section><footer><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="询问当前目录中的项目，Enter 发送" /><button className="primary-button" disabled={busy||!prompt.trim()} onClick={()=>void send()}><Send /></button></footer></>}{error&&<p className="ai-error">{error}</p>}</main></section>}</div>
}
