import { useCallback, useEffect, useState } from 'react'

type Incident = { id: string; processName: string; status: string; severity: string; occurrences: number; fingerprint: string; sample?: string; decisionReason?: string }
type Todo = { id: string; title: string; status: string; severity: string; reason: string }
type Maintenance = { id: string; incidentId: string; taskId?: string; status: string; error?: string; rollbackPerformed?: boolean }
type Metrics = { incidents: number; openTodos: number; maintenanceRuns: number; autoFixSuccess: number; rollbacks: number; resolved: number; averageRecoverySecs: number }
type Policy = { projectRoot: string; mode: 'off' | 'observe' | 'auto' | 'strict'; autoAllowed: boolean; allowCodeChanges: boolean; allowPm2Control: boolean; observationMinutes: number; maxModifiedFiles: number; maxPm2Actions: number }

export function OpsCenter({ root }: { root: string }) {
  const [incidents, setIncidents] = useState<Incident[]>([])
  const [todos, setTodos] = useState<Todo[]>([])
  const [maintenance, setMaintenance] = useState<Maintenance[]>([])
  const [metrics, setMetrics] = useState<Metrics | null>(null)
  const [policy, setPolicy] = useState<Policy>({ projectRoot: root, mode: 'observe', autoAllowed: false, allowCodeChanges: false, allowPm2Control: false, observationMinutes: 5, maxModifiedFiles: 10, maxPm2Actions: 3 })
  const [paused, setPaused] = useState(false)
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => {
    const [i, t, m, x, p] = await Promise.all([fetch('/api/v1/ops/incidents'), fetch('/api/v1/ops/todos'), fetch('/api/v1/ops/maintenance'), fetch('/api/v1/ops/metrics'), fetch(`/api/v1/ops/policy?root=${encodeURIComponent(root)}`)])
    if (i.ok) setIncidents(await i.json() as Incident[])
    if (t.ok) setTodos(await t.json() as Todo[])
    if (m.ok) setMaintenance(await m.json() as Maintenance[])
    if (x.ok) setMetrics(await x.json() as Metrics)
    if (p.ok) setPolicy(await p.json() as Policy)
  }, [root])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10000); return () => window.clearInterval(timer) }, [load])
  const post = async (path: string) => { setBusy(true); try { await fetch(path, { method: 'POST' }); await load() } finally { setBusy(false) } }
  const savePolicy = async () => { setBusy(true); try { await fetch('/api/v1/ops/policy', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(policy) }); await load() } finally { setBusy(false) } }
  return <section className="grid min-h-0 gap-4 overflow-auto p-5" aria-label="AI 运维中心">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">AI 运维中心</h1><p className="text-xs text-slate-500">{paused ? '监控已暂停' : '监控运行中'} · {root}</p></div><div className="flex gap-2"><button className="secondary-button" disabled={busy} onClick={() => { const next = !paused; setPaused(next); void post(`/api/v1/ops/monitor/${next ? 'pause' : 'resume'}`) }}>{paused ? '恢复采集' : '暂停采集'}</button><button className="secondary-button" disabled={busy} onClick={() => void post('/api/v1/ops/monitor/emergency-stop')}>紧急停止</button></div></header>
    {metrics && <div className="grid grid-cols-2 gap-2 md:grid-cols-5">{[['事件', metrics.incidents], ['待办', metrics.openTodos], ['维护', metrics.maintenanceRuns], ['已恢复', metrics.resolved], ['回滚', metrics.rollbacks]].map(([label, value]) => <div className="rounded-lg border border-slate-200 bg-white p-3" key={String(label)}><small className="text-xs text-slate-500">{label}</small><strong className="block text-lg">{value}</strong></div>)}</div>}
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">实时事件</h2>{incidents.slice(0, 12).map(item => <article className="mb-3 rounded-md border border-slate-100 p-3" key={item.id}><div className="flex justify-between"><strong>{item.processName} · {item.severity}</strong><small>{item.status} · {item.occurrences} 次</small></div><p className="mt-1 truncate text-xs text-slate-500">{item.sample || item.fingerprint}</p><small className="text-xs text-slate-400">{item.decisionReason || '等待策略分析'}</small><div className="mt-2 flex gap-2"><button className="agent-session-action" onClick={() => void post(`/api/v1/ops/incidents/${item.id}/analyze`)}>分析</button><button className="agent-session-action" onClick={() => void post(`/api/v1/ops/incidents/${item.id}/todo`)}>加入待办</button><button className="agent-session-action" onClick={() => void post(`/api/v1/ops/incidents/${item.id}/silence`)}>静默</button></div></article>)}{incidents.length === 0 && <p className="text-sm text-slate-500">暂无事件。</p>}</section><section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">待办与维护</h2>{todos.slice(0, 8).map(item => <article className="mb-2 rounded-md border border-slate-100 p-3" key={item.id}><strong>{item.title}</strong><small className="ml-2 text-xs text-slate-500">{item.status} · {item.severity}</small><p className="text-xs text-slate-500">{item.reason}</p></article>)}{maintenance.slice(0, 8).map(item => <article className="mb-2 rounded-md border border-slate-100 p-3" key={item.id}><strong>维护 {item.id}</strong><small className="ml-2 text-xs text-slate-500">{item.status}</small>{item.error && <p className="text-xs text-red-600">{item.error}</p>}<div className="mt-1 flex gap-2">{item.status === 'observing' && <button className="agent-session-action" onClick={() => void post(`/api/v1/ops/maintenance/${item.id}/observe`)}>结束观察</button>}{item.taskId && <button className="agent-session-action" onClick={() => void post(`/api/v1/ops/maintenance/${item.id}/rollback`)}>回滚</button>}</div></article>)}</section></div>
    <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="mb-3 font-semibold">AI 策略</h2><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-xs">模式<select value={policy.mode} onChange={event => setPolicy({ ...policy, mode: event.target.value as Policy['mode'] })}><option value="observe">观察</option><option value="auto">自动维护</option><option value="strict">严格确认</option><option value="off">关闭</option></select></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={policy.autoAllowed} onChange={event => setPolicy({ ...policy, autoAllowed: event.target.checked })} />项目白名单</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={policy.allowCodeChanges} onChange={event => setPolicy({ ...policy, allowCodeChanges: event.target.checked })} />允许代码修改</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={policy.allowPm2Control} onChange={event => setPolicy({ ...policy, allowPm2Control: event.target.checked })} />允许 PM2 控制</label><label className="grid gap-1 text-xs">观察分钟数<input type="number" min="1" value={policy.observationMinutes} onChange={event => setPolicy({ ...policy, observationMinutes: Number(event.target.value) || 1 })} /></label></div><button className="primary-button mt-3" disabled={busy} onClick={() => void savePolicy()}>保存策略</button></section>
  </section>
}
